name: Generate LocationIdMappingInfo JSON

on:
  push:
    branches:
      - main  # Adjust this based on your branch name
  workflow_dispatch:    
      

jobs:
  run-script:
    runs-on: ubuntu-latest  # You can choose a different OS if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cheching changes on repo
      run : |
            echo ${{ github.repository }}
            echo git diff --name-only ${{ github.event.before }} ${{ github.sha }};
            if git diff --quiet main...HEAD; then
            echo "No changes detected."
            else
            echo "no Changes detected."
            fi
